services:
  - type: web
    name: estore-api
    env: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn estore.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: estore-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: estore-db
    plan: free
    region: oregon